# Generated by Django 3.2 on 2021-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
