# Generated by Django 3.2 on 2021-05-23 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums',
            name='id_coment',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='id_forum',
        ),
        migrations.AddField(
            model_name='coment',
            name='id_forum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forums.forums'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forums',
            name='id_topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forums.topics'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Userforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', models.IntegerField(null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
