# Generated by Django 3.2 on 2021-05-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20210523_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforo',
            name='id_forum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forums.forums'),
            preserve_default=False,
        ),
    ]
