# Generated by Django 3.2 on 2021-05-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_userforo_id_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='replies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='forums',
            name='cant_coment',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Userforo',
        ),
    ]
