# Generated by Django 3.2 on 2021-05-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20210523_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='replies',
        ),
    ]
