# Generated by Django 3.2 on 2021-05-25 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_remove_coment_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='coment',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.coment'),
        ),
        migrations.AddField(
            model_name='coment',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coment',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='forums',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
