# Generated by Django 3.2 on 2021-05-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20210525_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='slug',
        ),
    ]
